---
swagger: "2.0"
info:
  description: "This is a done by gopaddle team"
  version: "v1"
  title: "Swagger based application"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "API Support"
    url: "http://www.swagger.io/support"
    email: "support@swagger.io"
  license:
    name: "apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/v1"
schemes:
- "http"
produces:
- "application/json"
paths:
  /demo-pyn:
    get:
      tags:
      - "default_controller"
      summary: "demo-pyn Type"
      description: "This endponits for get the specified demo-pyn resource"
      operationId: "controllers.default_controller.demo_pyn_get"
      parameters: []
      responses:
        200:
          description: "An array of demo-pyn"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/demo-pyn"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
      - "default_controller"
      summary: "demo-pyn Type"
      description: "This endponits for create a new demo-pyn resource"
      operationId: "controllers.default_controller.demo_pyn_post"
      parameters: []
      responses:
        200:
          description: "description about created resource of demo-pyn"
          schema:
            $ref: "#/definitions/demo-pyn"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /demo-pyn/{demo-pyn_id}:
    get:
      tags:
      - "default_controller"
      summary: "demo-pyn Type"
      description: "This endponits for get the specified demo-pyn resource"
      operationId: "controllers.default_controller.demo_pyn_demo_pyn_id_get"
      parameters:
      - name: "demo-pyn_id"
        in: "path"
        description: "Fetch resource id of the demo-pyn"
        required: true
        type: "string"
      responses:
        200:
          description: "description about created resource of demo-pyn"
          schema:
            $ref: "#/definitions/demo-pyn"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
    put:
      tags:
      - "default_controller"
      summary: "demo-pyn Type"
      description: "This endponits for update the specified demo-pyn resource"
      operationId: "controllers.default_controller.demo_pyn_demo_pyn_id_put"
      parameters:
      - name: "demo-pyn_id"
        in: "path"
        description: "Update resource id of the demo-pyn"
        required: true
        type: "string"
      responses:
        200:
          description: "description about updated resource of demo-pyn"
          schema:
            $ref: "#/definitions/demo-pyn"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
    delete:
      tags:
      - "default_controller"
      summary: "demo-pyn Type"
      description: "This endponits for delete the specified demo-pyn resource"
      operationId: "controllers.default_controller.demo_pyn_demo_pyn_id_delete"
      parameters:
      - name: "demo-pyn_id"
        in: "path"
        description: "Delete resource id of the demo-pyn"
        required: true
        type: "string"
      responses:
        204:
          description: "Resource deleted"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
definitions:
  demo-pyn:
    type: "object"
    properties:
      demo-pyn_id:
        type: "string"
        description: "Data field of demo-pyn_id"
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"
